### ISSUE TITLE
Socket.io 1.0 release

### ISSUE THREAD

**Issue by matteosuppo** [abourget/gevent-socketio#192]
It appears that socket.io 1.0 has been released: http://socket.io/blog/introducing-socket-io-1-0/

There are new protocols: https://github.com/automattic/engine.io-protocol and https://github.com/automattic/socket.io-protocol

**Comment by krishn2014** [comment]
Hi, can anyone give me pointer to start development for socket.io 1.3

**Comment by a740122** [comment]
https://github.com/shuoli84/gevent_socketio2
gevent_socketio2 can support socket.io 1.3 ?

**Comment by muatik** [comment]
Is supporting socket.io 1.x in your roadmap?

**Comment by krishn2014** [comment]
I do not think so, unless required for my project.

**Comment by dswarbrick** [comment]
I did some preliminary exploration and found that the first place where gevent-socketio breaks is in handler.SocketIOHandler, where it tries to identify socket.io requests with the RE_HANDSHAKE_URL regex. The socket.io protocol version 1.x uses a totally different URL pattern, as it is built on top of engine.io.

This quickly started to look like a larger task than I have time for (sentiments probably also felt by the developer of https://github.com/shuoli84/gevent_socketio2).

I had a brief play with with https://github.com/miguelgrinberg/python-socketio, and this appears to be a better solution for me personally (and the repo is actively maintained).
