### ISSUE TITLE
headers use integer for Access-Control-Max-Age

### ISSUE THREAD

**Issue by alon** [abourget/gevent-socketio#228]
Headers should be string/unicode (python 2/3) and this is being violated when Access-Control-Max-Age is set to 3600. It should be set to '3600' (str) instead:

see https://github.com/gevent/gevent/blob/master/gevent/pywsgi.py#L737which quotes Pep 3333 "The start_response callable" for the enforcement and see https://github.com/abourget/gevent-socketio/blob/master/socketio/handler.py#L77 for the offending code.

i.e. suggested patch (I can do a pull request if needed):

```
diff --git a/socketio/handler.py b/socketio/handler.py
index e4b972f..6bdb5b1 100644
--- a/socketio/handler.py
+++ b/socketio/handler.py
@@ -74,7 +74,7 @@ class SocketIOHandler(WSGIHandler):
             ("Access-Control-Allow-Origin", self.environ.get('HTTP_ORIGIN', '*')),
             ("Access-Control-Allow-Credentials", "true"),
             ("Access-Control-Allow-Methods", "POST, GET, OPTIONS"),
-            ("Access-Control-Max-Age", 3600),
+            ("Access-Control-Max-Age", str(3600)),
             ("Content-Type", "text/plain"),
         ])
         self.result = [data]
```
(edited for style)

**Comment by tshirtman** [comment]
Yes, getting the same issue, and was getting to the same cause, a pull request would be very useful :)
